# See http://www.appveyor.com/docs/appveyor-yml for many more options

version: 0.4.0.{build}

only_commits:
  files:
    - $env:APPVEYOR_PROJECT_NAME/
    - $env:APPVEYOR_PROJECT_NAME.nuspec
    - Tests/
    - appveyor.yml

skip_commits:
  files:
    - '**/*.md'

image:
- Visual Studio 2017
- Ubuntu

init:
- ps: |
    $PSVersionTable
    [System.Environment]::OSVersion

install:
- ps: |
    Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
    Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

build_script:
- ps: |
    Import-Module ./$env:APPVEYOR_PROJECT_NAME

test_script:
- ps: |
    Invoke-Pester -EnableExit
